### PR TITLE
Better travis + tox configuration

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by hawkowl** [comment]
For some reason there's a flaky test. @glyph @mithrandi ideas?

**Comment by hawkowl** [comment]
```

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/travis/build/twisted/axiom/axiom/test/test_upgrading.py", line 262, in checkException
    self.assertEqual(e.storeID, swordID)
  File "/home/travis/build/twisted/axiom/.tox/py26-twtrunk/lib/python2.6/site-packages/twisted/trial/_synctest.py", line 437, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/opt/python/2.6.9/lib/python2.6/unittest.py", line 350, in failUnlessEqual
    (msg or '%r != %r' % (first, second))
twisted.trial.unittest.FailTest: 2 != 1

axiom.test.test_upgrading.SubStoreCompat.test_basicErrorLogging
axiom.test.test_upgrading.SwordUpgradeTest.test_basicErrorLogging
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/travis/build/twisted/axiom/axiom/test/test_upgrading.py", line 189, in afterUpgrade
    self._testPlayerAndSwordState(player, sword)
  File "/home/travis/build/twisted/axiom/axiom/test/test_upgrading.py", line 364, in _testPlayerAndSwordState
    assert not sword.__legacy__
exceptions.AssertionError: 

axiom.test.test_upgrading.SubStoreCompat.testUpgradeWithMissingVersion
axiom.test.test_upgrading.SwordUpgradeTest.testUpgradeWithMissingVersion
-------------------------------------------------------------------------------
```

**Comment by mithrandi** [comment]
That failure doesn't look familiar at a glance; I'll take a look at the code in more detail later to see if I can figure it out. (Also, I reran the build just to see if the same builders failed, or different ones)

Does tox do anything strange with garbage collection?

**Comment by mithrandi** [comment]
Well, it seems pretty reproducible, at least; nearly all of the builders got that failure this time.

**Comment by mithrandi** [comment]
In short, this is a real bug that only occurs under certain dict orderings; tox randomizes `PYTHONHASHSEED` which is why the bug went undetected until now. See #48 for more information.

**Comment by glyph** [comment]
@mithrandi - you want to merge master since #49 has now been merged?

**Comment by mithrandi** [comment]
Replaced by #53.

**Pull request closed without merging**
