### PR TITLE
'except' syntax for python 3

### PR DESCRIPTION
**Pull request by glyph**
The simplest possible part of porting.

### CODE REVIEW

**Comment by hawkowl** [comment]
sure, land when green

**Comment by mithrandi** [comment]
:+1:

**Comment by mithrandi** [comment]
I'm not sure why the codecov commit status is missing, but I'm just going to go ahead and merge this anyway.

**Comment by hawkowl** [comment]
I think it's because we tightened the restrictions on 3rd party apps. Let me reauth it.

**Pull request merged**
